name: Update Ottawa Events

on:
  schedule:
    - cron: "0 0 1 * *"   # runs at midnight UTC on the 1st of every month
  workflow_dispatch:       # allow manual run too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run fetch
        env:
          EVENTBRITE_KEY: ${{ secrets.EVENTBRITE_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "Update events.json"
          git push